# Generated by Django 2.2.4 on 2020-06-03 02:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_added_normal', models.DateField(default=datetime.date.today)),
                ('state', models.TextField(default='Lagos', max_length=200, verbose_name='State')),
                ('month', models.TextField(default='June', max_length=200, verbose_name='Month')),
                ('year', models.CharField(default='2020', max_length=200, verbose_name='Year')),
                ('allocatedCoins', models.DecimalField(decimal_places=2, default=70000.0, max_digits=15, verbose_name='Allocated Coins')),
                ('backAllocatedCoins', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Back Allocated Coins')),
                ('exchangeRate', models.DecimalField(decimal_places=2, default=9.99, max_digits=5, verbose_name='Exchange Rate')),
            ],
        ),
        migrations.CreateModel(
            name='minedCoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miner', models.CharField(max_length=30, verbose_name='Miner')),
                ('creditedBy', models.CharField(max_length=30, verbose_name='Credit by Agent')),
                ('minedCoin', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Mined Coin')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_added_normal', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(default='Admin', max_length=30, verbose_name='Sender')),
                ('header', models.TextField(default='headings', max_length=2000, verbose_name='Header')),
                ('message', models.TextField(max_length=2000, verbose_name='Message')),
                ('receiver', models.CharField(default='0', max_length=30, verbose_name='Reciever')),
                ('beenRead', models.TextField(default='No', max_length=20, verbose_name='Read Message')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_added_normal', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30, verbose_name='User')),
                ('user_phone', models.CharField(max_length=15, null=True, unique=True, verbose_name='Telephone number')),
                ('otp_code', models.IntegerField(verbose_name='OTP')),
                ('validated', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('otp_reset_code', models.IntegerField(default='0000', max_length=20, verbose_name='Reset Code')),
            ],
        ),
        migrations.CreateModel(
            name='redeemCoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miner', models.CharField(max_length=30, verbose_name='Miner')),
                ('incentive', models.CharField(max_length=30, verbose_name='Incentive')),
                ('redeemedCoin', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Redeemed Coin')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_added_normal', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=30, verbose_name='Sender')),
                ('recipient', models.CharField(max_length=30, verbose_name='Recipient')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Amount of WasteCoin')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_added_normal', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='WastecoinUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=30, verbose_name='Firstname')),
                ('lastname', models.CharField(blank=True, max_length=30, verbose_name='Lastname')),
                ('email', models.EmailField(max_length=90, unique=True, verbose_name='Email')),
                ('user_phone', models.CharField(max_length=15, null=True, unique=True, verbose_name='Telephone number')),
                ('user_gender', models.CharField(max_length=15, verbose_name='Gender')),
                ('user_password', models.TextField(max_length=200, verbose_name='Password')),
                ('user_address', models.TextField(max_length=200, verbose_name='Address')),
                ('user_state', models.TextField(max_length=200, verbose_name='State')),
                ('user_lga', models.TextField(max_length=200, verbose_name='LGA')),
                ('user_country', models.TextField(max_length=200, verbose_name='Country')),
                ('accountname', models.TextField(blank=True, max_length=200, verbose_name='Account Name')),
                ('accountnumber', models.CharField(blank=True, max_length=10, null=True, verbose_name='Account Number')),
                ('bank', models.TextField(blank=True, max_length=200, verbose_name='Bank')),
                ('currentUserWastecoinBalance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Current WasteCoin Balance')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_added_normal', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WastecoinAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=30, verbose_name='Firstname')),
                ('lastname', models.CharField(blank=True, max_length=30, verbose_name='Lastname')),
                ('email', models.EmailField(max_length=90, unique=True, verbose_name='Email')),
                ('user_phone', models.CharField(max_length=15, null=True, unique=True, verbose_name='Telephone number')),
                ('user_gender', models.CharField(max_length=15, verbose_name='Gender')),
                ('user_password', models.TextField(max_length=200, verbose_name='Password')),
                ('user_address', models.TextField(max_length=200, verbose_name='Address')),
                ('user_state', models.TextField(max_length=200, verbose_name='State')),
                ('user_lga', models.TextField(max_length=200, verbose_name='LGA')),
                ('user_country', models.TextField(max_length=200, verbose_name='Country')),
                ('accountname', models.TextField(blank=True, max_length=200, verbose_name='Account Name')),
                ('accountnumber', models.CharField(blank=True, max_length=10, null=True, verbose_name='Account Number')),
                ('bank', models.TextField(blank=True, max_length=200, verbose_name='Bank')),
                ('currentAgentWastecoinBalance', models.DecimalField(decimal_places=2, default=5000.0, max_digits=15, verbose_name='Current WasteCoin Balance')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_added_normal', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
