# Generated by Django 2.2.4 on 2020-06-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastecoinapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_reset_code',
            field=models.IntegerField(default='0000', verbose_name='Reset Code'),
        ),
    ]
