# Generated by Django 2.2.4 on 2020-07-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastecoinapp', '0002_auto_20200603_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(default='NA', max_length=30, verbose_name='Transaction type'),
        ),
    ]
