# Generated by Django 2.2.4 on 2020-07-06 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wastecoinapp', '0003_transaction_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user_phone',
        ),
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
