# Generated by Django 2.2.4 on 2020-07-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wastecoinapp', '0004_auto_20200706_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='user',
            field=models.CharField(max_length=200, verbose_name='User'),
        ),
    ]
